### ISSUE TITLE
Problem parsing compile_command.json in Windows with Ninja build

### ISSUE THREAD

**Issue by enricodetoma** [viva64/pvs-studio-cmake-examples#10] opened 2019-04-05 08:05 UTC
`CompilerCommandsAnalyzer.exe` is unable to parse this `compile_command.json` generated on Windows using CMake + Ninja build:

	{
	  "directory": "E:/workingfolder/my-project/build",
	  "command": "C:\\PROGRA~2\\MICROS~1\\2017\\COMMUN~1\\VC\\Tools\\MSVC\\1416~1.270\\bin\\Hostx64\\x64\\cl.exe  /nologo /TP -DLOGGING_LIBRARY -DQTILITIESCORE_LIBRARY -DQTILITIES_CORE_GUI_LIBRARY -DQTILITIES_NO_HELP -DQTILITIES_VERSION_MAJOR=1 -DQTILITIES_VERSION_MINOR=5 -DQTILITIES_VERSION_REVISION=0 -DQT_CORE_LIB -DQT_GUI_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -DQtilities_EXPORTS -DWIN32_LEAN_AND_MEAN -D_SCL_SECURE_NO_WARNINGS -D_WIN32_WINNT=0x0601 -IQtilities\\Qtilities_autogen\\include -I..\\Qtilities\\include -I..\\Qtilities\\include\\QtilitiesCore -I..\\Qtilities\\include\\QtilitiesCoreGui -I..\\Qtilities\\include\\QtilitiesLogging -IE:\\DevTools\\Qt\\5.12.0\\msvc2017_64\\include -IE:\\DevTools\\Qt\\5.12.0\\msvc2017_64\\include\\QtXml -IE:\\DevTools\\Qt\\5.12.0\\msvc2017_64\\include\\QtCore -IE:\\DevTools\\Qt\\5.12.0\\msvc2017_64\\.\\mkspecs\\win32-msvc -IE:\\DevTools\\Qt\\5.12.0\\msvc2017_64\\include\\QtWidgets -IE:\\DevTools\\Qt\\5.12.0\\msvc2017_64\\include\\QtGui -IE:\\DevTools\\Qt\\5.12.0\\msvc2017_64\\include\\QtANGLE -IE:\\DevTools\\Qt\\5.12.0\\msvc2017_64\\include\\QtPrintSupport  /DWIN32 /D_WINDOWS /W3 /GR /EHsc /bigobj /std:c++17 /MDd /Z7 /Ob0 /Od /RTC1   /FoQtilities\\CMakeFiles\\Qtilities.dir\\Qtilities_autogen\\mocs_compilation.cpp.obj /FdTARGET_COMPILE_PDB /FS -c E:\\workingfolder\\my-project\\build\\Qtilities\\Qtilities_autogen\\mocs_compilation.cpp",
	  "file": "E:/workingfolder/my-project/build/Qtilities/Qtilities_autogen/mocs_compilation.cpp"
	},
	...

I tried running it with `--verbose` flag and I discovered that the problem lies in the `\\` in the paths, which get replaced to empty and the paths become invalid.
If I replace all `\\` with `/` in `compile_command.json`,  `CompilerCommandsAnalyzer.exe` works correctly and finds both the `cl.exe` compiler and the source files.

**Comment by SvyatoslavRazmyslov** [comment] 2019-04-07 19:05
Hello, @enricodetoma. We're going to reproduce and fix this behavior next week.

**Comment by rasjani** [comment] 2020-09-25 08:57
Evaluating pvs-studio and looks like this hasn't been fixed yet ?

**Comment by cerg2010cerg2010** [comment] 2020-09-30 09:38
This issue will be fixed in the next release. It appears that command string syntax is different between Windows and *nix, and it's not documented in the [spec](http://clang.llvm.org/docs/JSONCompilationDatabase.html).

Also see for explanation: https://github.com/jacobdufault/cquery/issues/73#issuecomment-346889157

The escape sequences will be ignored on Windows as a workaround.

**Closed by cerg2010cerg2010** 2020-09-30 09:38 UTC
